alertmanager:
  enabled: true

server:
  global:
    scrape_interval: 15s
  persistentVolume:
    enabled: true
    size: 10Gi
  service:
    type: ClusterIP
  retention: "15d"

rbac:
  create: true

serviceMonitors:
  enabled: true
  additionalServiceMonitors:
    - name: example-service
      namespace: default
      selector:
        matchLabels:
          app: example
      endpoints:
        - port: web
